azure_blob_store_container_name: producer

kafka:
  bootstrap-servers: localhost:9092 #pkc-4j8dq.southeastasia.azure.confluent.cloud:9092
  notification:
    topic: eacloud #test-compression
  headers:
    count: 1
    keys: X-DOCBROKER-Correlation-ID
  retry:
    topic: retry
  event: vv
  listener:
    topics: eacloud
    #group: vv-consumer
    #thread:
      #vv: 1
  #vv:
    #topic: eacloud




spring:
  retry:
    maximum:
      attempts: 3
  kafka:
    listener:
      ack-mode: manual-immediate
    consumer:
      bootstrap-servers: localhost:9092 #pkc-4j8dq.southeastasia.azure.confluent.cloud:9092
      auto-offset-reset: earliest
      fetch-max-wait: 3600
      enable-auto-commit: false
      group-id: group-2
      max-poll-records: 20
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      message:
        max:
          bytes: 2660050
      properties:
        fetch:
          max:
            bytes: 2660050
        max:
          partition:
            fetch:
              bytes: 2660050
        #ssl.endpoint.identification.algorithm: https
        #sasl.mechanism: PLAIN
        #sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="GK2CGDIYO5N2MYCB" password="MfYCpwaT8OrmmgUPPXTrKj0kvi5tQQMA++RiKZJbgYWPTg+4n81AqJjs3WsfDDVH";
        #security.protocol: SASL_SSL

    producer:
      bootstrap-servers: localhost:9092 #pkc-4j8dq.southeastasia.azure.confluent.cloud:9092
      properties:
        #ssl.endpoint.identification.algorithm: https
        #sasl.mechanism: PLAIN
        #sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="GK2CGDIYO5N2MYCB" password="MfYCpwaT8OrmmgUPPXTrKj0kvi5tQQMA++RiKZJbgYWPTg+4n81AqJjs3WsfDDVH";
        #security.protocol: SASL_SSL
        compression:
          type: gzip
        acks: all
        retries: 10000
        delivery:
          timeout:
            ms: 60000
        enable:
          idempotence: true
        max:
          in:
            flight:
              requests:
                per:
                  connection: 5
          #request:
            #size: 2660050

azure:
  storage:
    account-name: claimscheckpayloads
    account-key: 8OD1vjEqe7ux9m7UiBWImDMfmsWfu52rjkdsHoQ6gUrDyNThUt9U7UDeeEZWssp/IaVWv/CTXv8spi0Kug9gpA==
    blob-endpoint: https://claimscheckpayloads.core.windows.net
    endpoint-suffix: core.windows.net
    container-name: ${azure_blob_store_container_name}

events-payload:
  file-name: docbroker_response
  max-bytes: 20

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus